import { createChart, CandlestickSeries, HistogramSeries, LineSeries, CrosshairMode, createSeriesMarkers } from '/vendor/lightweight-charts.mjs';

const instruments = [
  { symbol: 'ESZ6', exchange: 'CME', root: 'ES', name: 'E-mini S&P 500', tick: 0.25 },
  { symbol: 'NQZ6', exchange: 'CME', root: 'NQ', name: 'E-mini Nasdaq 100', tick: 0.25 },
  { symbol: 'GCZ6', exchange: 'COMEX', root: 'GC', name: 'Gold Futures', tick: 0.1 },
];
let current = instruments[0], interval = 60, ws, chart, candle, line, footprintCanvas, symbolId, bars = [], last = null, bid = null, ask = null, side = 1, account = '', chartType = 'candles';
let memberAuthenticated = false, authenticatedStarted = false;
let vwapSeries, largeOrderMarkers, drawingCanvas, activeDrawingTool = null, drawingStart = null, drawingHover = null, indicatorFrame = 0, drawingFrame = 0;
let historyDays = 2, timeZone = 'Asia/Shanghai';
const HISTORY_DAYS_STORAGE_KEY = 'odt-history-days-v1', TIMEZONE_STORAGE_KEY = 'odt-timezone-v1', MAX_HISTORY_DAYS = 3650;
const TIMEZONES = [{ id: 'America/New_York', label: '纽约' }, { id: 'Asia/Shanghai', label: '北京' }];
const realTimeByChart = new Map();
const PERIOD_STORAGE_KEY = 'odt-periods-v2', LEGACY_PERIOD_STORAGE_KEY = 'odt-periods-v1';
const DEFAULT_PERIODS = [{ type: 'time', value: 60 }, { type: 'time', value: 300 }, { type: 'time', value: 900 }, { type: 'time', value: 3600 }, { type: 'time', value: 86400 }];
const WEEK_SECONDS = 604800, MONTH_SECONDS = 2592000, YEAR_SECONDS = 31536000;
const PERIOD_GROUPS = [
  { name: '秒', items: [1, 5, 15, 30].map((v) => ({ type: 'time', value: v })) },
  { name: '分钟', items: [1, 2, 3, 5, 10, 15, 30, 45].map((v) => ({ type: 'time', value: v * 60 })) },
  { name: '小时', items: [1, 2, 4, 6, 8, 12].map((v) => ({ type: 'time', value: v * 3600 })) },
  { name: '天以上', items: [{ type: 'time', value: 86400 }, { type: 'time', value: WEEK_SECONDS }, { type: 'time', value: MONTH_SECONDS }, { type: 'time', value: YEAR_SECONDS }] },
  { name: 'Range', items: [2, 4, 8, 16, 32].map((v) => ({ type: 'range', value: v })) },
  { name: 'Tick', items: [100, 250, 500, 1000, 2000].map((v) => ({ type: 'tick', value: v })) },
];
let favoritePeriods = DEFAULT_PERIODS.slice();
let period = { type: 'time', value: 60 }, customPeriods = [];
let historyRequestSeq = 0, lastMarketTime = 0, lastLiveEventAt = 0;
let depthBook = new Map();
let menthorqLines = [], menthorqTimer = null, menthorqRequestSeq = 0, menthorqVisible = true, menthorqLevels = [];
const MENTHORQ_STORAGE_KEY = 'odt-menthorq-settings-v1';
const MIN_MARKET_TIME = 946684800;
const MAX_MARKET_TIME_SKEW = 86400;
const $ = (id) => document.getElementById(id);
const OVERLAY_STORAGE_KEY = 'odt-chart-overlays-v1';
const INDICATOR_SETTINGS_KEY = 'odt-indicator-settings-v1', DRAWINGS_STORAGE_KEY = 'odt-chart-drawings-v1';
const OVERLAY_DEFAULTS = { menthorq: true, largeOrders: false, vwap: false };
const INDICATOR_DEFAULTS = { largeOrders: { threshold: 50, buyColor: '#29c78a', sellColor: '#f05d6c', labels: true }, vwap: { anchor: 'session', sessionStart: '18:00', customTime: '', source: 'hlc3', color: '#f2bb59', lineWidth: 2 } };
let largeOrdersVisible = false, vwapVisible = false, indicatorSettings = structuredClone(INDICATOR_DEFAULTS), drawingsBySymbol = {};
const fmt = (v, digits = current.tick === 0.1 ? 1 : 2) => v == null || !Number.isFinite(Number(v)) ? '--' : Number(v).toLocaleString('en-US', { minimumFractionDigits: digits, maximumFractionDigits: digits });
const show = (message, ms = 3600) => { $('order-message').textContent = message; window.clearTimeout(show.timer); show.timer = window.setTimeout(() => $('order-message').textContent = '', ms); };

function initChart() {
  loadOverlaySettings();
  chart = createChart($('chart'), { autoSize: true, layout: { background: { type: 'solid', color: '#0d121a' }, textColor: '#78879a' }, grid: { vertLines: { color: '#18212c' }, horzLines: { color: '#18212c' } }, crosshair: { mode: CrosshairMode.Magnet }, rightPriceScale: { borderColor: '#202b39', autoScale: true }, timeScale: { borderColor: '#202b39', rightOffset: 5, timeVisible: true, secondsVisible: false, tickMarkFormatter: formatChartTime }, localization: { timeFormatter: formatChartTime } });
  candle = chart.addSeries(CandlestickSeries, { upColor: '#29c78a', downColor: '#f05d6c', borderVisible: false, wickUpColor: '#29c78a', wickDownColor: '#f05d6c', priceFormat: { type: 'price', precision: current.tick === 0.1 ? 1 : 2, minMove: current.tick } });
  line = chart.addSeries(LineSeries, { color: '#52d4df', lineWidth: 2, visible: false, priceFormat: { type: 'price', precision: current.tick === 0.1 ? 1 : 2, minMove: current.tick } });
  vwapSeries = chart.addSeries(LineSeries, { color: indicatorSettings.vwap.color, lineWidth: indicatorSettings.vwap.lineWidth, visible: false, priceLineVisible: false, lastValueVisible: true, title: 'VWAP', priceFormat: { type: 'price', precision: current.tick === 0.1 ? 1 : 2, minMove: current.tick } });
  largeOrderMarkers = createSeriesMarkers(candle, []);
  footprintCanvas = document.createElement('canvas');
  footprintCanvas.className = 'footprint-layer';
  $('chart').appendChild(footprintCanvas);
  drawingCanvas = document.createElement('canvas');
  drawingCanvas.className = 'drawing-layer';
  drawingCanvas.setAttribute('aria-label', '图表绘图工具层');
  $('chart').appendChild(drawingCanvas);
  chart.timeScale().subscribeVisibleLogicalRangeChange(() => { scheduleFootprintDraw(); scheduleDrawingDraw(); if (vwapVisible && indicatorSettings.vwap.anchor === 'visible') scheduleIndicators(); });
  new ResizeObserver(() => { scheduleFootprintDraw(); scheduleDrawingDraw(); }).observe($('chart'));
  initDrawingTools();
  chart.timeScale().fitContent();
  $('fit-chart').onclick = () => { if (chartType === 'footprint') { chart.timeScale().applyOptions({ barSpacing: 118, rightOffset: 2 }); chart.timeScale().scrollToRealTime(); } else { chart.timeScale().fitContent(); } chart.priceScale('right').applyOptions({ autoScale: true }); scheduleFootprintDraw(); };
  document.querySelectorAll('#chart-types button').forEach((button) => button.onclick = () => setChartType(button.dataset.chartType));
  initOverlays($('indicators-menu'));
}
let footprintFrame = 0;
function scheduleFootprintDraw() {
  cancelAnimationFrame(footprintFrame);
  footprintFrame = requestAnimationFrame(drawFootprint);
}
function footprintNumber(value) {
  const n = Number(value || 0);
  if (Math.abs(n) >= 1e6) return `${(n / 1e6).toFixed(1)}m`;
  if (Math.abs(n) >= 1e3) return `${(n / 1e3).toFixed(1)}k`;
  return Number.isInteger(n) ? String(n) : n.toFixed(1);
}
function drawFootprint() {
  if (!footprintCanvas) return;
  const host = $('chart'), rect = host.getBoundingClientRect(), dpr = window.devicePixelRatio || 1;
  const width = Math.max(1, Math.round(rect.width)), height = Math.max(1, Math.round(rect.height));
  if (footprintCanvas.width !== Math.round(width * dpr) || footprintCanvas.height !== Math.round(height * dpr)) {
    footprintCanvas.width = Math.round(width * dpr);
    footprintCanvas.height = Math.round(height * dpr);
    footprintCanvas.style.width = `${width}px`;
    footprintCanvas.style.height = `${height}px`;
  }
  const ctx = footprintCanvas.getContext('2d');
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  ctx.clearRect(0, 0, width, height);
  if (chartType !== 'footprint') return;
  ctx.font = '10px ui-monospace, SFMono-Regular, Consolas, monospace';
  ctx.textBaseline = 'middle';
  const plotted = bars.map((bar) => ({ bar, x: chart.timeScale().timeToCoordinate(chartBar(bar).time) })).filter((item) => Number.isFinite(item.x));
  const visible = plotted.filter(({ x }) => x >= -80 && x <= width + 80);
  const visibleLevels = visible.flatMap(({ bar }) => (Array.isArray(bar.levels) ? bar.levels : []).filter((level) => {
    const y = candle.priceToCoordinate(Number(level.price));
    return Number.isFinite(y) && y >= 0 && y <= height;
  }));
  const visibleMaxDelta = Math.max(1, ...visibleLevels.map((level) => Math.abs(Number(level.ask || 0) - Number(level.bid || 0))));
  const visibleMaxVolume = Math.max(1, ...visibleLevels.map((level) => Number(level.bid || 0) + Number(level.ask || 0) + Number(level.neutral || 0)));
  for (let index = 0; index < plotted.length; index += 1) {
    const { bar, x } = plotted[index];
    if (x < -160 || x > width + 160) continue;
    const previousX = plotted[index - 1]?.x, nextX = plotted[index + 1]?.x;
    const spacing = Math.abs(Number.isFinite(nextX) ? nextX - x : Number.isFinite(previousX) ? x - previousX : 118);
    const barWidth = Math.min(156, Math.max(38, spacing * 0.9));
    const levels = Array.isArray(bar.levels) ? bar.levels : [];
    const barDelta = levels.reduce((sum, level) => sum + Number(level.ask || 0) - Number(level.bid || 0), 0);
    const highY = candle.priceToCoordinate(Number(bar.high));
    if (Number.isFinite(highY)) {
      ctx.fillStyle = barDelta >= 0 ? '#55dca6' : '#ff7b88';
      ctx.textAlign = 'center';
      ctx.fillText(`Δ${barDelta >= 0 ? '+' : ''}${footprintNumber(barDelta)}`, x, Math.max(8, highY - 9));
    }
    if (!levels.length || barWidth < 72) continue;
    const tickY = candle.priceToCoordinate(Number(levels[0].price) + current.tick);
    const baseY = candle.priceToCoordinate(Number(levels[0].price));
    const rowHeight = Math.abs(Number(tickY) - Number(baseY));
    if (!Number.isFinite(rowHeight) || rowHeight < 9) continue;
    const cellHeight = Math.min(22, Math.max(9, rowHeight));
    const left = x - barWidth / 2, leftWidth = barWidth * 0.68, divider = left + leftWidth, rightWidth = barWidth - leftWidth;
    const poc = levels.reduce((best, level) => Number(level.bid || 0) + Number(level.ask || 0) + Number(level.neutral || 0) > Number(best.bid || 0) + Number(best.ask || 0) + Number(best.neutral || 0) ? level : best, levels[0]);
    for (const level of levels) {
      const y = candle.priceToCoordinate(Number(level.price));
      if (!Number.isFinite(y) || y < -cellHeight || y > height + cellHeight) continue;
      const bidVolume = Number(level.bid || 0), askVolume = Number(level.ask || 0), neutralVolume = Number(level.neutral || 0);
      const delta = askVolume - bidVolume, totalVolume = bidVolume + askVolume + neutralVolume;
      const deltaRatio = Math.min(1, Math.abs(delta) / visibleMaxDelta), volumeRatio = Math.min(1, totalVolume / visibleMaxVolume);
      const top = y - cellHeight / 2;
      ctx.fillStyle = delta >= 0 ? `rgba(41,199,138,${0.1 + 0.56 * deltaRatio})` : `rgba(240,93,108,${0.1 + 0.56 * deltaRatio})`;
      ctx.fillRect(divider - leftWidth * deltaRatio, top, leftWidth * deltaRatio, cellHeight);
      ctx.fillStyle = `rgba(82,212,223,${0.08 + 0.54 * volumeRatio})`;
      ctx.fillRect(divider, top, rightWidth * volumeRatio, cellHeight);
      ctx.strokeStyle = level === poc ? '#f2bb59' : 'rgba(120,135,154,.24)';
      ctx.lineWidth = level === poc ? 1.25 : 0.5;
      ctx.strokeRect(left, top, barWidth, cellHeight);
      ctx.strokeStyle = 'rgba(232,237,243,.35)';
      ctx.beginPath(); ctx.moveTo(divider, top + 1); ctx.lineTo(divider, top + cellHeight - 1); ctx.stroke();
      ctx.fillStyle = '#f3f6fa';
      ctx.textAlign = 'center';
      ctx.fillText(`${footprintNumber(bidVolume)} × ${footprintNumber(askVolume)}`, left + leftWidth / 2, y);
      ctx.fillStyle = '#d8fbff';
      ctx.fillText(footprintNumber(totalVolume), divider + rightWidth / 2, y);
    }
  }
}
function buildTabs() { $('symbol-tabs').innerHTML = instruments.map((item, i) => `<button class="${i === 0 ? 'active' : ''}" data-symbol="${item.symbol}">${item.root}<small>${item.symbol.slice(-1)}</small></button>`).join(''); document.querySelectorAll('#symbol-tabs button').forEach((button) => button.onclick = () => selectInstrument(instruments.find((item) => item.symbol === button.dataset.symbol))); }
let depthLocked = false;
function depthPriceKey(price) { const tick = Number(current?.tick) || 0.01; return Math.round(Number(price) / tick); }
function depthRowHtml(row, cls) { return `<div class="depth-row ${cls}"><span>${row.bid ? Number(row.bid).toLocaleString() : ''}</span><span class="price">${fmt(row.price)}</span><span>${row.ask ? Number(row.ask).toLocaleString() : ''}</span></div>`; }
function drawDepth() { const el = $('depth'); if (!el) return; const byPrice = new Map(); depthBook.forEach((row) => { const key = depthPriceKey(row.price); const entry = byPrice.get(key) || { price: Number(row.price), bid: 0, ask: 0 }; entry[row.side] = Number(entry[row.side] || 0) + Number(row.quantity || 0); byPrice.set(key, entry); }); if (depthLocked && Number.isFinite(Number(last))) { const tick = Number(current?.tick) || 0.01; const center = depthPriceKey(last); const rowsEach = Math.max(5, Math.floor(((el.clientHeight || 300) / 23 - 1) / 2)); const rows = []; for (let k = center + rowsEach; k >= center - rowsEach; k -= 1) { const entry = byPrice.get(k) || { price: k * tick, bid: 0, ask: 0 }; const cls = k === center ? 'last' : entry.ask ? 'ask' : entry.bid ? 'bid' : 'empty'; rows.push(depthRowHtml(entry, cls)); } el.innerHTML = rows.join(''); return; } const asks = [...byPrice.values()].filter((r) => r.ask).sort((a, b) => b.price - a.price).slice(-10); const bids = [...byPrice.values()].filter((r) => r.bid).sort((a, b) => b.price - a.price).slice(0, 10); el.innerHTML = [...asks.map((r) => depthRowHtml({ ...r, bid: 0 }, 'ask')), ...bids.map((r) => depthRowHtml({ ...r, ask: 0 }, 'bid'))].join(''); }
function renderDepth(levels, replace = false) { if (!levels?.length) return; if (replace) depthBook = new Map(); levels.filter(Boolean).forEach((row) => { const key = `${row.side}:${row.level ?? row.price}`; if (row.action === 'delete' || Number(row.quantity) <= 0) depthBook.delete(key); else depthBook.set(key, row); }); drawDepth(); }
$('depth-lock')?.addEventListener('click', () => { depthLocked = !depthLocked; $('depth-lock').classList.toggle('active', depthLocked); drawDepth(); });

async function loadHistory(refresh = false) { const requestSeq = ++historyRequestSeq; const requestedInstrument = current; const requestedPeriod = period; const requestedType = chartType; const days = historyDays; const orderflow = needsOrderflowHistory(); const query = `symbol=${encodeURIComponent(requestedInstrument.symbol)}&exchange=${encodeURIComponent(requestedInstrument.exchange)}&${periodQuery(requestedPeriod)}&days=${days}${orderflow ? '&footprint=1' : ''}${refresh ? '&refresh=1' : ''}`; setDownloadBusy(true, `下载 ${days} 天 Rithmic 历史…`); try { const barResponse = await fetch(`/api/history?${query}`); const payload = await barResponse.json(); if (!barResponse.ok || !payload.bars) throw new Error(payload.error || `HTTP ${barResponse.status}`); if (requestSeq !== historyRequestSeq || current.symbol !== requestedInstrument.symbol || period !== requestedPeriod || chartType !== requestedType) return; bars = normalizeBars(payload.bars); applyChartData(); const latest = bars[bars.length - 1]; if (latest) { if (last == null) last = latest.close; if (!lastMarketTime) lastMarketTime = latest.time; $('stat-open').textContent = fmt(bars[0].open); $('stat-high').textContent = fmt(Math.max(...bars.map((bar) => bar.high))); $('stat-low').textContent = fmt(Math.min(...bars.map((bar) => bar.low))); $('stat-volume').textContent = Math.round(bars.reduce((sum, bar) => sum + Number(bar.volume || 0), 0)).toLocaleString(); if (!lastLiveEventAt) $('feed-time').textContent = sourceLabel(payload.source); } if (payload.warning) show(payload.warning, 6000); else if (refresh) show(`已加载 ${bars.length} 根K线 · ${payload.days || days} 天 · ${sourceLabel(payload.source)}`); renderQuote(false); fitChart(); scheduleFootprintDraw(); scheduleDrawingDraw(); } catch (error) { console.error('[History]', error); if (requestSeq === historyRequestSeq && current.symbol === requestedInstrument.symbol && period === requestedPeriod) show(`History unavailable: ${error.message}`); return; } finally { if (requestSeq === historyRequestSeq) setDownloadBusy(false); } }
function fitChart() { if (chartType === 'footprint') { chart.timeScale().applyOptions({ barSpacing: 118, rightOffset: 2 }); chart.timeScale().scrollToRealTime(); } else chart.timeScale().fitContent(); scheduleFootprintDraw(); }
function sourceLabel(source) { return { 'local-cache': 'Rithmic 本地缓存', 'local-cache-stale': 'Rithmic 本地缓存（刷新失败）', 'rithmic': 'Rithmic 历史', 'rithmic-ticks': 'Rithmic 成交明细', 'rithmic+live': 'Rithmic 成交明细 + 实时成交', 'live-trades': 'Rithmic 实时成交（启动后累积）' }[source] || source || '未知来源'; }
function setDownloadBusy(busy, text) { const button = $('history-download'); if (button) { button.disabled = busy; button.textContent = busy ? '下载中…' : '下载'; } if (busy && text && !lastLiveEventAt) $('feed-time').textContent = text; }
function initHistoryDays() { const stored = Math.floor(Number(localStorage.getItem(HISTORY_DAYS_STORAGE_KEY))); if (stored >= 1 && stored <= MAX_HISTORY_DAYS) historyDays = stored; $('history-days').value = String(historyDays); const download = () => { const value = Math.floor(Number($('history-days').value)); if (!(value >= 1 && value <= MAX_HISTORY_DAYS)) return show(`天数需在 1 到 ${MAX_HISTORY_DAYS} 之间`); historyDays = value; localStorage.setItem(HISTORY_DAYS_STORAGE_KEY, String(value)); historyRequestSeq += 1; loadHistory(true); }; $('history-download').onclick = download; $('history-days').onkeydown = (event) => { if (event.key === 'Enter') download(); }; }
function selectPeriod(item) { period = item; interval = period.type === 'time' ? period.value : 60; savePeriods(); renderPeriods(); const needed = recommendedDays(item); if (needed > historyDays) { historyDays = needed; $('history-days').value = String(needed); localStorage.setItem(HISTORY_DAYS_STORAGE_KEY, String(needed)); show(`已将下载天数调整为 ${needed} 天以覆盖 ${periodLabel(item)} 周期`); } historyRequestSeq += 1; bars = []; realTimeByChart.clear(); candle.setData([]); line.setData([]); loadHistory(); }
function setChartType(type) { if (!['candles', 'line', 'footprint'].includes(type) || type === chartType) return; chartType = type; document.querySelectorAll('#chart-types button').forEach((b) => b.classList.toggle('active', b.dataset.chartType === type)); candle.applyOptions({ visible: type !== 'line', upColor: type === 'footprint' ? 'rgba(41,199,138,.12)' : '#29c78a', downColor: type === 'footprint' ? 'rgba(240,93,108,.12)' : '#f05d6c', borderVisible: type === 'footprint', borderUpColor: '#29c78a', borderDownColor: '#f05d6c' }); line.applyOptions({ visible: type === 'line' }); chart.timeScale().applyOptions({ barSpacing: type === 'footprint' ? 118 : 6 }); scheduleFootprintDraw(); if (type === 'footprint' && period.type !== 'time') { show('足迹图已切换到 1 分钟周期'); selectPeriod(DEFAULT_PERIODS[0]); return; } loadHistory(); }
function mergeFootprintLevels(a = [], b = []) { const levels = new Map(); [...a, ...b].forEach((level) => { const key = Math.round(Number(level.price) / current.tick); const value = levels.get(key) || { price: key * current.tick, bid: 0, ask: 0, neutral: 0, maxBid: 0, maxAsk: 0, maxNeutral: 0 }; value.bid += Number(level.bid || 0); value.ask += Number(level.ask || 0); value.neutral += Number(level.neutral || 0); value.maxBid = Math.max(value.maxBid, Number(level.maxBid || 0)); value.maxAsk = Math.max(value.maxAsk, Number(level.maxAsk || 0)); value.maxNeutral = Math.max(value.maxNeutral, Number(level.maxNeutral || 0)); levels.set(key, value); }); return [...levels.values()].sort((x, y) => x.price - y.price); }
function normalizeBars(list) { realTimeByChart.clear(); const merged = new Map(); (list || []).filter((bar) => Number.isFinite(Number(bar.time))).forEach((raw) => { const time = bucketStart(Number(raw.time)); const bar = { ...raw, time, levels: Array.isArray(raw.levels) ? raw.levels : [] }; const existing = merged.get(time); if (!existing) { merged.set(time, bar); return; } merged.set(time, { ...existing, high: Math.max(Number(existing.high), Number(bar.high)), low: Math.min(Number(existing.low), Number(bar.low)), close: bar.close, volume: Number(existing.volume || 0) + Number(bar.volume || 0), trades: Number(existing.trades || 0) + Number(bar.trades || 0), levels: mergeFootprintLevels(existing.levels, bar.levels) }); }); const sorted = [...merged.values()].sort((a, b) => a.time - b.time); const step = period.type === 'time' ? period.value * 1000 : 1000; const first = sorted[0]?.time || 0; sorted.forEach((bar, index) => { bar.chartTime = first * 1000 + index * step; }); return sorted; }
function chartStepMs() { return period.type === 'time' ? period.value * 1000 : 1000; }
function periodQuery(item) { if (item.type === 'tick') return `barType=tick&barSize=${item.value}&interval=0`; if (item.type === 'range') return `barType=range&barSize=${item.value}&interval=0`; return `interval=${item.value}`; }
function periodLabel(item) { if (item.type === 'tick') return `${item.value}T`; if (item.type === 'range') return `${item.value}R`; const v = item.value; if (v === YEAR_SECONDS) return '1Y'; if (v === MONTH_SECONDS) return '1M'; if (v === WEEK_SECONDS) return '1W'; if (v % 86400 === 0) return `${v / 86400}D`; if (v % 3600 === 0) return `${v / 3600}h`; if (v % 60 === 0) return `${v / 60}m`; return `${v}s`; }
function periodTitle(item) { if (item.type === 'tick') return `${item.value} 笔成交 / 根`; if (item.type === 'range') return `${item.value} 个最小变动 / 根`; const v = item.value; if (v === YEAR_SECONDS) return '年线（按日历年）'; if (v === MONTH_SECONDS) return '月线（按日历月）'; if (v === WEEK_SECONDS) return '周线（周一开始）'; if (v % 86400 === 0) return `${v / 86400} 天`; if (v % 3600 === 0) return `${v / 3600} 小时`; if (v % 60 === 0) return `${v / 60} 分钟`; return `${v} 秒`; }
function isCalendarPeriod(item) { return item.type === 'time' && [WEEK_SECONDS, MONTH_SECONDS, YEAR_SECONDS].includes(item.value); }
// Start of the bar holding `seconds` for the current period. Calendar sizes
// mirror the server: the clock is shifted eight hours so an evening session
// open books to its trading date, then snapped to Monday / the 1st / 1 Jan.
function bucketStart(seconds) { if (period.type !== 'time') return seconds; const v = period.value; if (!isCalendarPeriod(period)) return Math.floor(seconds / v) * v; const date = new Date((seconds + 8 * 3600) * 1000); const utcDay = Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()); if (v === WEEK_SECONDS) { const dow = (date.getUTCDay() + 6) % 7; return utcDay / 1000 - dow * 86400; } if (v === MONTH_SECONDS) return Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), 1) / 1000; return Date.UTC(date.getUTCFullYear(), 0, 1) / 1000; }
function recommendedDays(item) { if (item.type !== 'time') return 0; if (item.value === YEAR_SECONDS || item.value === MONTH_SECONDS) return 3650; if (item.value === WEEK_SECONDS) return 1095; if (item.value >= 86400) return 365; return 0; }
function samePeriod(a, b) { return a.type === b.type && a.value === b.value; }
function validPeriod(item) { return item && ['time', 'tick', 'range'].includes(item.type) && Number.isInteger(item.value) && item.value > 0; }
function knownPeriods() { return [...PERIOD_GROUPS.flatMap((group) => group.items), ...customPeriods]; }
function loadPeriods() { try { const stored = JSON.parse(localStorage.getItem(PERIOD_STORAGE_KEY) || localStorage.getItem(LEGACY_PERIOD_STORAGE_KEY) || '{}'); customPeriods = (stored.custom || []).filter(validPeriod).filter((item) => !PERIOD_GROUPS.some((group) => group.items.some((preset) => samePeriod(preset, item)))); favoritePeriods = Array.isArray(stored.favorites) ? stored.favorites.filter(validPeriod) : [...DEFAULT_PERIODS, ...customPeriods]; if (!favoritePeriods.length) favoritePeriods = DEFAULT_PERIODS.slice(); const selected = stored.selected; if (validPeriod(selected)) period = selected; } catch { customPeriods = []; favoritePeriods = DEFAULT_PERIODS.slice(); } interval = period.type === 'time' ? period.value : 60; }
function savePeriods() { localStorage.setItem(PERIOD_STORAGE_KEY, JSON.stringify({ custom: customPeriods, favorites: favoritePeriods, selected: period })); }
function isFavorite(item) { return favoritePeriods.some((entry) => samePeriod(entry, item)); }
function toggleFavorite(item) { if (isFavorite(item)) favoritePeriods = favoritePeriods.filter((entry) => !samePeriod(entry, item)); else favoritePeriods.push(item); savePeriods(); renderPeriods(); }
function renderPeriods() { const bar = favoritePeriods.slice(); if (!bar.some((item) => samePeriod(item, period))) bar.push(period); $('intervals').innerHTML = bar.map((item) => `<button data-type="${item.type}" data-value="${item.value}" class="${samePeriod(item, period) ? 'active' : ''}" title="${periodTitle(item)}">${periodLabel(item)}</button>`).join(''); document.querySelectorAll('#intervals button').forEach((button) => { button.onclick = () => selectPeriod({ type: button.dataset.type, value: Number(button.dataset.value) }); }); renderPeriodPanel(); }
function periodItemHtml(item, custom) { return `<span class="period-item${samePeriod(item, period) ? ' active' : ''}" data-type="${item.type}" data-value="${item.value}"><button class="pick" title="${periodTitle(item)}">${periodLabel(item)}</button><button class="star${isFavorite(item) ? ' on' : ''}" title="固定到工具栏">★</button>${custom ? '<button class="remove" title="删除">×</button>' : ''}</span>`; }
function renderPeriodPanel() { const groups = PERIOD_GROUPS.map((group) => `<div class="period-group"><span class="period-group-name">${group.name}</span><div class="period-group-items">${group.items.map((item) => periodItemHtml(item, false)).join('')}</div></div>`); if (customPeriods.length) groups.push(`<div class="period-group"><span class="period-group-name">自定义</span><div class="period-group-items">${customPeriods.map((item) => periodItemHtml(item, true)).join('')}</div></div>`); $('period-groups').innerHTML = groups.join(''); document.querySelectorAll('#period-groups .period-item').forEach((node) => { const item = { type: node.dataset.type, value: Number(node.dataset.value) }; node.querySelector('.pick').onclick = () => { $('period-editor').classList.add('hidden'); selectPeriod(item); }; node.querySelector('.star').onclick = () => toggleFavorite(item); const remove = node.querySelector('.remove'); if (remove) remove.onclick = () => { customPeriods = customPeriods.filter((entry) => !samePeriod(entry, item)); favoritePeriods = favoritePeriods.filter((entry) => !samePeriod(entry, item)); if (samePeriod(period, item)) selectPeriod(DEFAULT_PERIODS[0]); else { savePeriods(); renderPeriods(); } }; }); }
function addCustomPeriod() { const type = $('period-type').value; const value = Math.floor(Number($('period-value').value)); if (!Number.isFinite(value) || value < 1) return show('请输入有效的周期数值'); let item; if (type === 'tick') { if (value < 2) return show('Tick 周期至少 2 笔'); item = { type: 'tick', value }; } else if (type === 'range') item = { type: 'range', value }; else if (type === 'week' || type === 'month' || type === 'year') { if (value !== 1) return show('周 / 月 / 年周期目前仅支持 1 个单位'); item = { type: 'time', value: type === 'week' ? WEEK_SECONDS : type === 'month' ? MONTH_SECONDS : YEAR_SECONDS }; } else item = { type: 'time', value: type === 'day' ? value * 86400 : type === 'hour' ? value * 3600 : type === 'minute' ? value * 60 : value }; if (item.type === 'time' && item.value > 86400 * 7 && !isCalendarPeriod(item)) return show('天周期最长 7 天'); if (!knownPeriods().some((entry) => samePeriod(entry, item))) customPeriods.push(item); if (!isFavorite(item)) favoritePeriods.push(item); $('period-editor').classList.add('hidden'); selectPeriod(item); }
function initPeriods() { loadPeriods(); renderPeriods(); $('period-add').onclick = (event) => { event.stopPropagation(); $('period-editor').classList.toggle('hidden'); if (!$('period-editor').classList.contains('hidden')) $('period-value').focus(); }; $('period-editor').onclick = (event) => event.stopPropagation(); document.addEventListener('click', () => $('period-editor').classList.add('hidden')); $('period-save').onclick = addCustomPeriod; $('period-value').onkeydown = (event) => { if (event.key === 'Enter') addCustomPeriod(); }; }
function selectInstrument(item) { setDrawingTool(null); current = item; symbolId = null; historyRequestSeq += 1; menthorqRequestSeq += 1; lastLiveEventAt = 0; document.querySelectorAll('#symbol-tabs button').forEach((b) => b.classList.toggle('active', b.dataset.symbol === item.symbol)); $('instrument-name').textContent = item.symbol; $('instrument-meta').textContent = `${item.exchange} · ${item.name}`; $('price').step = String(item.tick); $('feed-time').textContent = 'Feed waiting'; bars = []; last = bid = ask = null; lastMarketTime = 0; depthBook = new Map(); candle.setData([]); line.setData([]); vwapSeries.setData([]); largeOrderMarkers.setMarkers([]); $('depth').replaceChildren(); clearMenthorqLines(); subscribe(); loadHistory(); scheduleDrawingDraw(); if ($('mq-api-key').value.trim()) fetchMenthorqLevels(); }
function handle(message) { if (message.type === 'historyProgress') { const log = message.stage === 'error' ? console.error : console.info; log(`[History][${message.stage || 'info'}] ${message.symbol || ''}.${message.exchange || ''} [${message.period || ''}] ${Number(message.percent) >= 0 ? `${message.percent}% ` : ''}${message.detail || ''}`); return; } if (message.type === 'ready') { $('mode-badge').textContent = message.tradingConnected ? 'PAPER' : 'READ ONLY'; setFeedStatus(Boolean(message.feedAvailable)); refreshAccount(); return; } if (message.type === 'feed') { setFeedStatus(Boolean(message.available)); return; } if (message.type === 'subscribed') { if (message.symbol !== current.symbol || message.exchange !== current.exchange) return; symbolId = message.symbolId; return; } if (message.symbolId != null && message.symbolId !== symbolId) return; if (message.type === 'snapshot' || message.type === 'snapshotEvent') updateSnapshot(message.data); if (message.type === 'quote') { bid = message.bid; ask = message.ask; lastMarketTime = validMarketTime(message.time) || lastMarketTime; lastLiveEventAt = Date.now(); renderQuote(false); updateLiveRange(); $('feed-time').textContent = `Live ${formatTime(lastMarketTime || Math.floor(Date.now()/1000))}`; renderDepth([{ side: 'bid', price: bid, quantity: message.bidSize, level: 1 }, { side: 'ask', price: ask, quantity: message.askSize, level: 1 }]); } if (message.type === 'trade') updateTrade(message); if (message.type === 'depth') renderDepth(message.levels, true); if (message.type === 'depthLevel' || message.type === 'depthUpdate') renderDepth(message.level ? [message.level] : []); if (message.type === 'volume') $('stat-volume').textContent = Number(message.volume).toLocaleString(); if (message.type === 'order' || message.type === 'position' || message.type === 'balance') refreshAccount(); if (message.type === 'error' || message.type === 'warning') { $('feed-time').textContent = message.message; show(message.message); if (message.type === 'error' && !message.symbolId) connectionRefreshSoon(); } }
function connect() { if (!memberAuthenticated) return; const protocol = location.protocol === 'https:' ? 'wss:' : 'ws:'; ws = new WebSocket(`${protocol}//${location.host}/ws`); ws.onopen = () => { $('connection-label').textContent = 'Connected'; $('connection-dot').classList.add('live'); subscribe(); loadHistory(); }; ws.onerror = () => { $('connection-label').textContent = 'Connection error'; $('connection-dot').classList.remove('live'); }; ws.onclose = () => { $('connection-label').textContent = memberAuthenticated ? 'Reconnecting' : '会员未登录'; $('connection-dot').classList.remove('live'); if (memberAuthenticated) window.setTimeout(connect, 1800); }; ws.onmessage = (event) => { try { handle(JSON.parse(event.data)); } catch (error) { show(`Feed message error: ${error.message}`); } }; }
function subscribe() { if (ws?.readyState === WebSocket.OPEN) ws.send(JSON.stringify({ type: 'subscribe', symbol: current.symbol, exchange: current.exchange })); }
function updateSnapshot(data) { last = data.last ?? last; bid = data.bid ?? bid; ask = data.ask ?? ask; lastMarketTime = validMarketTime(data.time) || lastMarketTime; lastLiveEventAt = Date.now(); $('stat-open').textContent = fmt(data.open); $('stat-high').textContent = fmt(data.high); $('stat-low').textContent = fmt(data.low); $('stat-volume').textContent = data.volume == null ? '--' : Number(data.volume).toLocaleString(); $('stat-oi').textContent = data.openInterest == null ? '--' : Number(data.openInterest).toLocaleString(); renderQuote(false); $('feed-time').textContent = `Live snapshot ${formatTime(lastMarketTime || Math.floor(Date.now()/1000))}`; }
function setFeedStatus(available) { $('connection-label').textContent = available ? 'Server Data Live' : 'Server Data reconnecting'; $('connection-dot').classList.toggle('live', available); if (!available) $('feed-time').textContent = 'Waiting for server data'; connectionRefreshSoon(); }
function formatTime(seconds, dayMark = false) { if (!Number.isFinite(seconds)) return ''; const options = dayMark ? { month: '2-digit', day: '2-digit' } : { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false }; return new Intl.DateTimeFormat('zh-CN', { timeZone, ...options }).format(new Date(seconds * 1000)); }
function formatChartTime(time, tickMarkType) { const chartSeconds = Number(time); if (!Number.isFinite(chartSeconds)) return ''; return formatTime(realTimeByChart.get(Math.floor(chartSeconds)) ?? chartSeconds, Number.isInteger(tickMarkType) && tickMarkType <= 2); }
function setTimezone(id) { if (!TIMEZONES.some((zone) => zone.id === id)) return; timeZone = id; localStorage.setItem(TIMEZONE_STORAGE_KEY, id); document.querySelectorAll('#tz-toggle button').forEach((b) => b.classList.toggle('active', b.dataset.tz === id)); if (chart) chart.applyOptions({ localization: { timeFormatter: (value) => formatChartTime(value) }, timeScale: { tickMarkFormatter: (value, type) => formatChartTime(value, type) } }); if (lastLiveEventAt && lastMarketTime) $('feed-time').textContent = `Live ${formatTime(lastMarketTime)}`; }
function initTimezone() { const stored = localStorage.getItem(TIMEZONE_STORAGE_KEY); if (TIMEZONES.some((zone) => zone.id === stored)) timeZone = stored; $('tz-toggle').innerHTML = TIMEZONES.map((zone) => `<button data-tz="${zone.id}" class="${zone.id === timeZone ? 'active' : ''}" title="${zone.id}">${zone.label}</button>`).join(''); document.querySelectorAll('#tz-toggle button').forEach((b) => b.onclick = () => setTimezone(b.dataset.tz)); setTimezone(timeZone); }
function validMarketTime(value) { const seconds = Number(value); const now = Math.floor(Date.now() / 1000); return Number.isFinite(seconds) && seconds >= MIN_MARKET_TIME && seconds <= now + MAX_MARKET_TIME_SKEW ? Math.floor(seconds) : 0; }
function renderQuote(updateCandle = true) { $('last-price').textContent = fmt(last); if (depthLocked) drawDepth(); $('quote-line').textContent = `Bid ${fmt(bid)} · Ask ${fmt(ask)}`; if (!updateCandle || !bars.length || last == null || !Number.isFinite(Number(last))) return; const requestedTime = bucketStart(validMarketTime(lastMarketTime) || Math.floor(Date.now() / 1000)); const previous = bars[bars.length - 1]; const sameBar = previous != null && requestedTime <= Number(previous.time); const next = sameBar ? { ...previous, high: Math.max(Number(previous.high), Number(last)), low: Math.min(Number(previous.low), Number(last)), close: Number(last) } : { time: requestedTime, chartTime: Number(previous?.chartTime || 0) + chartStepMs(), open: Number(last), high: Number(last), low: Number(last), close: Number(last), volume: 0 }; if (sameBar) bars[bars.length - 1] = next; else bars.push(next); updateChartBar(next); $('change').textContent = previous ? `${last >= previous.close ? '+' : ''}${fmt(last - previous.close)}` : '--'; }
function chartBar(bar) { const time = Math.floor(Number(bar.chartTime ?? Number(bar.time) * 1000) / 1000); realTimeByChart.set(time, Math.floor(Number(bar.time))); return { time, open: Number(bar.open), high: Number(bar.high), low: Number(bar.low), close: Number(bar.close) }; }
function chartBars() { return bars.map(chartBar); }
function applyChartData() { candle.setData(chartBars()); line.setData(bars.map((bar) => ({ time: chartBar(bar).time, value: Number(bar.close) }))); renderMenthorqLines(); renderIndicators(); scheduleFootprintDraw(); scheduleDrawingDraw(); }
function updateChartBar(bar) { const data = chartBar(bar); candle.update(data); line.update({ time: data.time, value: data.close }); scheduleFootprintDraw(); scheduleIndicators(); scheduleDrawingDraw(); }
function updateLiveRange() { if (period.type !== 'time' || !bars.length || (!Number.isFinite(Number(bid)) && !Number.isFinite(Number(ask)))) return; const previous = bars[bars.length - 1]; const currentTime = bucketStart(validMarketTime(lastMarketTime) || Math.floor(Date.now() / 1000)); if (!previous || currentTime > Number(previous.time)) return; const prices = [previous.high, previous.low, bid, ask].map(Number).filter(Number.isFinite); const next = { ...previous, high: Math.max(...prices), low: Math.min(...prices) }; if (next.high === previous.high && next.low === previous.low) return; bars[bars.length - 1] = next; updateChartBar(next); }
function applyTradeToBar(trade) { const price = Number(trade.price); if (!Number.isFinite(price)) return; const volume = Number(trade.volume || 0); const micro = Number(trade.timeUs); const time = Number.isFinite(micro) && micro > 0 ? micro / 1e6 : (validMarketTime(trade.time) || Date.now() / 1000); const previous = bars[bars.length - 1]; const openBar = () => { const bar = { time: previous ? Math.max(time, previous.time + 0.001) : time, open: price, high: price, low: price, close: price, volume, trades: 1 }; bars.push(bar); updateChartBar(bar); }; const extend = (bar) => { bar.high = Math.max(Number(bar.high), price); bar.low = Math.min(Number(bar.low), price); bar.close = price; bar.volume = Number(bar.volume || 0) + volume; bar.trades = Number(bar.trades || 0) + 1; updateChartBar(bar); }; if (period.type === 'tick') { if (previous && Number(previous.trades || 0) < period.value) extend(previous); else openBar(); } else if (period.type === 'range') { const range = period.value * current.tick; if (previous && Math.max(Number(previous.high), price) - Math.min(Number(previous.low), price) <= range + 1e-9) extend(previous); else { if (previous) { previous.close = Math.min(Math.max(price, Number(previous.high) - range), Number(previous.low) + range); previous.high = Math.max(Number(previous.high), previous.close); previous.low = Math.min(Number(previous.low), previous.close); updateChartBar(previous); } openBar(); } } const reference = bars[bars.length - 2]; $('change').textContent = reference ? `${price >= reference.close ? '+' : ''}${fmt(price - reference.close)}` : '--'; }
function applyTradeToFootprint(trade) { const price = Number(trade.price), volume = Number(trade.volume || 0); if (!Number.isFinite(price)) return; const time = validMarketTime(trade.time) || Math.floor(Date.now() / 1000), requestedTime = bucketStart(time), previous = bars[bars.length - 1]; let bar; if (previous && requestedTime <= Number(previous.time)) { if (requestedTime !== Number(previous.time)) return; bar = previous; } else { bar = { time: requestedTime, chartTime: Number(previous?.chartTime || requestedTime * 1000) + (previous ? chartStepMs() : 0), open: price, high: price, low: price, close: price, volume: 0, trades: 0, levels: [] }; bars.push(bar); } bar.high = Math.max(Number(bar.high), price); bar.low = Math.min(Number(bar.low), price); bar.close = price; bar.volume = Number(bar.volume || 0) + volume; bar.trades = Number(bar.trades || 0) + 1; const key = Math.round(price / current.tick), level = bar.levels.find((item) => Math.round(Number(item.price) / current.tick) === key) || { price: key * current.tick, bid: 0, ask: 0, neutral: 0, maxBid: 0, maxAsk: 0, maxNeutral: 0 }; if (!bar.levels.includes(level)) bar.levels.push(level); if (Number(trade.atBidOrAsk) === 1) { level.bid += volume; level.maxBid = Math.max(Number(level.maxBid || 0), volume); } else if (Number(trade.atBidOrAsk) === 2) { level.ask += volume; level.maxAsk = Math.max(Number(level.maxAsk || 0), volume); } else { level.neutral += volume; level.maxNeutral = Math.max(Number(level.maxNeutral || 0), volume); } updateChartBar(bar); }
function updateTrade(trade) { last = Number(trade.price); lastMarketTime = validMarketTime(trade.time) || lastMarketTime; lastLiveEventAt = Date.now(); if (period.type === 'time' && needsLiveTradeAggregation()) { applyTradeToFootprint(trade); renderQuote(false); } else if (period.type === 'time') renderQuote(true); else { applyTradeToBar(trade); renderQuote(false); } const displayTime = validMarketTime(trade.time) || Math.floor(Date.now()/1000); $('feed-time').textContent = `Live ${formatTime(displayTime)}`; }
function symbolDrawings() { return drawingsBySymbol[current.symbol] || []; }
function needsOrderflowHistory() { return chartType === 'footprint' || largeOrdersVisible || activeDrawingTool === 'vp' || symbolDrawings().some((item) => item.type === 'vp'); }
function needsLiveTradeAggregation() { return needsOrderflowHistory() || vwapVisible; }
function scheduleIndicators() { cancelAnimationFrame(indicatorFrame); indicatorFrame = requestAnimationFrame(renderIndicators); }
function priceSource(bar, source) { if (source === 'close') return Number(bar.close); if (source === 'ohlc4') return (Number(bar.open) + Number(bar.high) + Number(bar.low) + Number(bar.close)) / 4; return (Number(bar.high) + Number(bar.low) + Number(bar.close)) / 3; }
const NEW_YORK_PARTS = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/New_York', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' });
function newYorkParts(seconds) { const result = {}; NEW_YORK_PARTS.formatToParts(new Date(Number(seconds) * 1000)).forEach((part) => { if (part.type !== 'literal') result[part.type] = Number(part.value); }); return result; }
function vwapGroupKey(seconds, anchor) { const p = newYorkParts(seconds); let day = Date.UTC(p.year, p.month - 1, p.day); if (anchor === 'session') { const [hour, minute] = String(indicatorSettings.vwap.sessionStart || '18:00').split(':').map(Number); if (p.hour * 60 + p.minute >= hour * 60 + minute) day += 86400000; return `s:${day}`; } if (anchor === 'week') { const dow = (new Date(day).getUTCDay() + 6) % 7; return `w:${day - dow * 86400000}`; } if (anchor === 'month') return `m:${p.year}-${p.month}`; if (anchor === 'year') return `y:${p.year}`; return 'custom'; }
function calculateVwap() { if (!vwapVisible || !bars.length) return []; const settings = indicatorSettings.vwap; let startIndex = 0; if (settings.anchor === 'visible') { const range = chart.timeScale().getVisibleLogicalRange(); startIndex = Math.max(0, Math.floor(Number(range?.from) || 0)); } else if (settings.anchor === 'custom') { const anchor = Date.parse(settings.customTime || '') / 1000; if (Number.isFinite(anchor)) { startIndex = bars.findIndex((bar) => Number(bar.time) >= anchor); if (startIndex < 0) return []; } }
  let group = null, cumulativePriceVolume = 0, cumulativeVolume = 0; const result = [];
  for (let index = startIndex; index < bars.length; index += 1) { const bar = bars[index]; const nextGroup = ['session', 'week', 'month', 'year'].includes(settings.anchor) ? vwapGroupKey(bar.time, settings.anchor) : 'anchor'; if (nextGroup !== group) { group = nextGroup; cumulativePriceVolume = 0; cumulativeVolume = 0; } const volume = Math.max(0, Number(bar.volume || 0)); if (volume > 0) { cumulativePriceVolume += priceSource(bar, settings.source) * volume; cumulativeVolume += volume; } if (cumulativeVolume > 0) result.push({ time: chartBar(bar).time, value: cumulativePriceVolume / cumulativeVolume }); }
  return result;
}
function largeOrderMarkerData() { if (!largeOrdersVisible) return []; const threshold = Math.max(1, Number(indicatorSettings.largeOrders.threshold) || 1), markers = []; for (const bar of bars) { const time = chartBar(bar).time; for (const level of bar.levels || []) { const ask = Number(level.maxAsk || 0), bidVolume = Number(level.maxBid || 0), neutral = Number(level.maxNeutral || 0), price = Number(level.price); if (ask >= threshold) markers.push({ time, position: 'belowBar', shape: 'arrowUp', color: indicatorSettings.largeOrders.buyColor, text: indicatorSettings.largeOrders.labels ? `${footprintNumber(ask)} @ ${fmt(price)}` : '' }); if (bidVolume >= threshold) markers.push({ time, position: 'aboveBar', shape: 'arrowDown', color: indicatorSettings.largeOrders.sellColor, text: indicatorSettings.largeOrders.labels ? `${footprintNumber(bidVolume)} @ ${fmt(price)}` : '' }); if (neutral >= threshold) markers.push({ time, position: 'inBar', shape: 'circle', color: '#f2bb59', text: indicatorSettings.largeOrders.labels ? `${footprintNumber(neutral)} @ ${fmt(price)}` : '' }); } } return markers.slice(-800); }
function renderIndicators() { if (!vwapSeries || !largeOrderMarkers) return; vwapSeries.applyOptions({ visible: vwapVisible, color: indicatorSettings.vwap.color, lineWidth: Number(indicatorSettings.vwap.lineWidth) }); vwapSeries.setData(calculateVwap()); largeOrderMarkers.setMarkers(largeOrderMarkerData()); refreshIndicatorButton(); }
function scheduleDrawingDraw() { cancelAnimationFrame(drawingFrame); drawingFrame = requestAnimationFrame(drawDrawingLayer); }
function saveDrawings() { localStorage.setItem(DRAWINGS_STORAGE_KEY, JSON.stringify(drawingsBySymbol)); }
function nearestBarByTime(time) { if (!bars.length) return null; let low = 0, high = bars.length - 1; while (low < high) { const mid = Math.floor((low + high) / 2); if (Number(bars[mid].time) < Number(time)) low = mid + 1; else high = mid; } if (low > 0 && Math.abs(Number(bars[low - 1].time) - Number(time)) < Math.abs(Number(bars[low].time) - Number(time))) low -= 1; return bars[low]; }
function barX(time) { const bar = nearestBarByTime(time); return bar ? chart.timeScale().timeToCoordinate(chartBar(bar).time) : null; }
function drawingPoint(event) { const rect = drawingCanvas.getBoundingClientRect(), x = event.clientX - rect.left, y = event.clientY - rect.top, logical = chart.timeScale().coordinateToLogical(x), index = Math.max(0, Math.min(bars.length - 1, Math.round(Number(logical)))); const bar = bars[index], price = candle.coordinateToPrice(y); return bar && Number.isFinite(Number(price)) ? { time: Number(bar.time), price: Number(price), x, y } : null; }
function setDrawingTool(tool) { activeDrawingTool = activeDrawingTool === tool ? null : tool; drawingStart = drawingHover = null; drawingCanvas.classList.toggle('active', Boolean(activeDrawingTool)); document.querySelectorAll('[data-drawing-tool]').forEach((button) => button.classList.toggle('active', button.dataset.drawingTool === activeDrawingTool)); if (activeDrawingTool === 'vp' && !bars.some((bar) => bar.levels?.length)) loadHistory(); scheduleDrawingDraw(); }
function initDrawingTools() { document.querySelectorAll('[data-drawing-tool]').forEach((button) => button.onclick = () => setDrawingTool(button.dataset.drawingTool)); $('drawing-clear').onclick = () => { if (!symbolDrawings().length || confirm(`清除 ${current.symbol} 的全部绘图？`)) { drawingsBySymbol[current.symbol] = []; saveDrawings(); scheduleDrawingDraw(); } }; drawingCanvas.onpointermove = (event) => { if (!activeDrawingTool || !drawingStart) return; drawingHover = drawingPoint(event); scheduleDrawingDraw(); }; drawingCanvas.onpointerleave = () => { drawingHover = null; scheduleDrawingDraw(); }; drawingCanvas.onclick = (event) => { if (!activeDrawingTool || !bars.length) return; const point = drawingPoint(event); if (!point) return; if (!drawingStart) { drawingStart = point; drawingHover = point; scheduleDrawingDraw(); return; } const drawing = activeDrawingTool === 'trend' ? { type: 'trend', startTime: drawingStart.time, startPrice: drawingStart.price, endTime: point.time, endPrice: point.price } : { type: 'vp', startTime: Math.min(drawingStart.time, point.time), endTime: Math.max(drawingStart.time, point.time) }; drawingsBySymbol[current.symbol] = [...symbolDrawings(), drawing]; saveDrawings(); drawingStart = drawingHover = null; setDrawingTool(null); scheduleDrawingDraw(); }; }
function addVolumeAtPrice(profile, price, volume) { const key = Math.round(Number(price) / current.tick); profile.set(key, Number(profile.get(key) || 0) + Number(volume || 0)); }
function volumeProfile(startTime, endTime) { const selected = bars.filter((bar) => Number(bar.time) >= startTime && Number(bar.time) <= endTime), profile = new Map(); for (const bar of selected) { if (bar.levels?.length) { bar.levels.forEach((level) => addVolumeAtPrice(profile, level.price, Number(level.bid || 0) + Number(level.ask || 0) + Number(level.neutral || 0))); continue; } const low = Math.round(Number(bar.low) / current.tick), high = Math.round(Number(bar.high) / current.tick), count = Math.max(1, high - low + 1), volume = Number(bar.volume || 0) / count; for (let key = low; key <= high && key < low + 500; key += 1) profile.set(key, Number(profile.get(key) || 0) + volume); } return profile; }
function drawTrend(ctx, drawing, preview = false) { const x1 = barX(drawing.startTime), x2 = barX(drawing.endTime), y1 = candle.priceToCoordinate(drawing.startPrice), y2 = candle.priceToCoordinate(drawing.endPrice); if (![x1, x2, y1, y2].every(Number.isFinite)) return; ctx.strokeStyle = preview ? '#9aa8b8' : '#52d4df'; ctx.lineWidth = 1.5; ctx.setLineDash(preview ? [5, 4] : []); ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke(); ctx.setLineDash([]); for (const [x, y] of [[x1, y1], [x2, y2]]) { ctx.fillStyle = '#0d121a'; ctx.strokeStyle = '#52d4df'; ctx.beginPath(); ctx.arc(x, y, 3.5, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); } }
function drawVolumeProfile(ctx, drawing, preview = false) { const x1 = barX(drawing.startTime), x2 = barX(drawing.endTime); if (![x1, x2].every(Number.isFinite)) return; const left = Math.min(x1, x2), right = Math.max(x1, x2), profile = volumeProfile(drawing.startTime, drawing.endTime), entries = [...profile.entries()]; if (!entries.length) return; const max = Math.max(...entries.map(([, volume]) => volume), 1), poc = entries.reduce((best, item) => item[1] > best[1] ? item : best, entries[0]); ctx.setLineDash([4, 4]); ctx.strokeStyle = preview ? '#78879a' : 'rgba(82,212,223,.65)'; ctx.strokeRect(left, 4, Math.max(1, right - left), drawingCanvas.clientHeight - 8); ctx.setLineDash([]); for (const [key, volume] of entries) { const price = key * current.tick, y = candle.priceToCoordinate(price), nextY = candle.priceToCoordinate(price + current.tick); if (!Number.isFinite(y)) continue; const height = Math.max(2, Math.min(18, Math.abs(Number(nextY) - y) || 5)), width = Math.min(Math.max(24, right - left), Math.max(2, (right - left) * volume / max)); ctx.fillStyle = key === poc[0] ? 'rgba(242,187,89,.72)' : preview ? 'rgba(120,135,154,.25)' : 'rgba(82,212,223,.34)'; ctx.fillRect(right - width, y - height / 2, width, height); } const pocY = candle.priceToCoordinate(poc[0] * current.tick); if (Number.isFinite(pocY)) { ctx.fillStyle = '#f2bb59'; ctx.font = '11px ui-monospace,monospace'; ctx.textAlign = 'right'; ctx.fillText(`VP POC ${fmt(poc[0] * current.tick)}`, right - 4, Math.max(12, pocY - 6)); } }
function drawDrawingLayer() { if (!drawingCanvas) return; const rect = drawingCanvas.getBoundingClientRect(), dpr = window.devicePixelRatio || 1, width = Math.max(1, Math.round(rect.width)), height = Math.max(1, Math.round(rect.height)); if (drawingCanvas.width !== Math.round(width * dpr) || drawingCanvas.height !== Math.round(height * dpr)) { drawingCanvas.width = Math.round(width * dpr); drawingCanvas.height = Math.round(height * dpr); drawingCanvas.style.width = `${width}px`; drawingCanvas.style.height = `${height}px`; } const ctx = drawingCanvas.getContext('2d'); ctx.setTransform(dpr, 0, 0, dpr, 0, 0); ctx.clearRect(0, 0, width, height); for (const drawing of symbolDrawings()) { if (drawing.type === 'trend') drawTrend(ctx, drawing); else if (drawing.type === 'vp') drawVolumeProfile(ctx, drawing); } if (drawingStart && drawingHover) { if (activeDrawingTool === 'trend') drawTrend(ctx, { type: 'trend', startTime: drawingStart.time, startPrice: drawingStart.price, endTime: drawingHover.time, endPrice: drawingHover.price }, true); else if (activeDrawingTool === 'vp') drawVolumeProfile(ctx, { type: 'vp', startTime: Math.min(drawingStart.time, drawingHover.time), endTime: Math.max(drawingStart.time, drawingHover.time) }, true); } }
async function refreshAccount() { try { const response = await fetch('/api/account'); const data = await response.json(); if (!data.enabled) { account = ''; $('account-select').innerHTML = '<option value="">Trading disabled</option>'; $('mode-badge').textContent = 'READ ONLY'; renderPositions([]); renderOrders([]); return; } const accounts = data.accounts || []; $('account-select').innerHTML = accounts.length ? accounts.map((item) => `<option value="${item.accountId}">${item.accountId}</option>`).join('') : '<option value="">No account</option>'; account = accounts[0]?.accountId || ''; $('mode-badge').textContent = 'PAPER'; renderPositions(data.positions || []); renderOrders(data.orders || []); } catch {} }
function renderPositions(items) { $('positions-list').innerHTML = items.length ? `<table class="data-table"><thead><tr><th>Symbol</th><th>Qty</th><th>Avg</th><th>P/L</th></tr></thead><tbody>${items.map((p)=>`<tr><td>${p.symbol}</td><td>${p.quantity}</td><td>${fmt(p.averagePrice)}</td><td class="${p.openPnl >= 0 ? 'positive':'negative'}">${fmt(p.openPnl)}</td></tr>`).join('')}</tbody></table>` : '<div class="empty-state">No open positions</div>'; }
function renderOrders(items) { $('order-count').textContent = items.length; $('orders-list').innerHTML = items.length ? `<table class="data-table"><thead><tr><th>Symbol</th><th>Side</th><th>Qty</th><th>Price</th><th></th></tr></thead><tbody>${items.map((o)=>`<tr><td>${o.symbol}</td><td class="${o.side===1?'positive':'negative'}">${o.side===1?'BUY':'SELL'}</td><td>${o.remaining}</td><td>${fmt(o.price1)}</td><td><button class="cancel" data-server="${o.serverOrderId}" data-client="${o.clientOrderId}">Cancel</button></td></tr>`).join('')}</tbody></table>` : '<div class="empty-state">No working orders</div>'; document.querySelectorAll('.cancel').forEach((b)=>b.onclick=()=>cancelOrder(b.dataset.server,b.dataset.client)); }
async function cancelOrder(serverOrderId, clientOrderId) { try { const response = await fetch('/api/cancel',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({server_order_id:serverOrderId,client_order_id:clientOrderId,account_id:account})}); const data=await response.json(); show(data.ok?'Cancel sent':data.error); refreshAccount(); } catch (error) { show(error.message); } }
async function submitOrder() { const type = Number($('order-type').value), price1 = Number($('price').value || 0), price2 = Number($('price2').value || 0), quantity = Number($('quantity').value), clientOrderId = $('client-order-id').value.trim() || `web-${Date.now()}`; if (!account) return show('No Paper trading account available'); if (type !== 1 && (!price1 || !Number.isFinite(price1))) return show('Enter a valid price'); if (!confirm(`${side===1?'BUY':'SELL'} ${quantity} ${current.symbol} ${type===1?'MARKET':`@ ${price1}`}. Submit Paper order?`)) return; const request={symbol:current.symbol,exchange:current.exchange,account_id:account,client_order_id:clientOrderId,order_type:type,buy_sell:side,price1,price2,quantity,time_in_force:1,is_automated:false}; try { const response=await fetch('/api/order',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(request)}); const data=await response.json(); show(data.ok?'Order accepted by gateway':data.error); if(data.ok){ $('client-order-id').value=''; refreshAccount(); } } catch(error){show(error.message);} }

function clearMenthorqLines() { menthorqLines.forEach(({ series, priceLine }) => { try { series.removePriceLine(priceLine); } catch {} }); menthorqLines = []; const list = $('menthorq-level-list'); if (list) list.replaceChildren(); }
function drawMenthorqOverlays() { if (!chart || !bars.length) return; menthorqLevels.forEach((item) => { const color = menthorqColor(item.name); const priceLine = candle.createPriceLine({ price: Number(item.price), color, lineWidth: 1, lineStyle: 2, axisLabelVisible: true, title: `MQ ${item.name}` }); menthorqLines.push({ series: candle, priceLine }); }); }
function initMenthorq() { loadMenthorqSettings(); $('menthorq-settings-open').onclick = openMenthorqSettings; $('menthorq-settings-close').onclick = closeMenthorqSettings; $('menthorq-settings-backdrop').onclick = closeMenthorqSettings; $('menthorq-save').onclick = () => { const settings = saveMenthorqSettings(); closeMenthorqSettings(); if (settings.apiKey) fetchMenthorqLevels(); else { $('menthorq-status').textContent = 'MQ 未配置'; $('menthorq-status').className = ''; } }; $('menthorq-clear').onclick = () => { $('mq-api-key').value = ''; menthorqLevels = []; clearMenthorqLines(); localStorage.removeItem(MENTHORQ_STORAGE_KEY); $('menthorq-status').textContent = 'MQ 未配置'; $('menthorq-status').className = ''; $('menthorq-message').textContent = '已清除 API Key'; $('menthorq-message').classList.remove('error'); refreshIndicatorButton(); }; const settings = menthorqFormSettings(); scheduleMenthorqRefresh(settings.refreshMinutes); if (settings.apiKey) fetchMenthorqLevels(); }
function openMenthorqSettings() { $('menthorq-settings').classList.add('open'); $('menthorq-settings').setAttribute('aria-hidden', 'false'); $('menthorq-settings-backdrop').classList.remove('hidden'); }
function closeMenthorqSettings() { $('menthorq-settings').classList.remove('open'); $('menthorq-settings').setAttribute('aria-hidden', 'true'); $('menthorq-settings-backdrop').classList.add('hidden'); }
function selectedMenthorqTypes() { return [...document.querySelectorAll('[name="mq-level-type"]:checked')].map((item) => item.value); }
function menthorqFormSettings() { return { apiUrl: $('mq-api-url').value.trim(), apiKey: $('mq-api-key').value.trim(), platform: $('mq-platform').value.trim(), userId: $('mq-user-id').value.trim(), tickers: { ES: $('mq-ticker-es').value.trim().toUpperCase(), NQ: $('mq-ticker-nq').value.trim().toUpperCase(), GC: $('mq-ticker-gc').value.trim().toUpperCase() }, levelTypes: selectedMenthorqTypes(), refreshMinutes: Math.max(0, Math.min(120, Number($('mq-refresh-minutes').value) || 0)), persistKey: $('mq-persist-key').checked }; }
function applyMenthorqSettings(settings = {}) { $('mq-api-url').value = settings.apiUrl || 'https://api.menthorq.io/getDailyLevels'; $('mq-api-key').value = settings.apiKey || ''; $('mq-platform').value = settings.platform || 'atas'; $('mq-user-id').value = settings.userId || 'userId'; $('mq-ticker-es').value = settings.tickers?.ES || 'ES'; $('mq-ticker-nq').value = settings.tickers?.NQ || 'NQ'; $('mq-ticker-gc').value = settings.tickers?.GC || 'GC'; $('mq-refresh-minutes').value = String(settings.refreshMinutes ?? 5); $('mq-persist-key').checked = settings.persistKey !== false; if (Array.isArray(settings.levelTypes)) document.querySelectorAll('[name="mq-level-type"]').forEach((item) => { item.checked = settings.levelTypes.includes(item.value); }); }
function loadMenthorqSettings() { try { applyMenthorqSettings(JSON.parse(localStorage.getItem(MENTHORQ_STORAGE_KEY) || '{}')); } catch { applyMenthorqSettings(); } }
function saveMenthorqSettings() { const settings = menthorqFormSettings(); const stored = { ...settings, apiKey: settings.persistKey ? settings.apiKey : '' }; localStorage.setItem(MENTHORQ_STORAGE_KEY, JSON.stringify(stored)); scheduleMenthorqRefresh(settings.refreshMinutes); return settings; }
function scheduleMenthorqRefresh(minutes) { window.clearInterval(menthorqTimer); menthorqTimer = minutes > 0 ? window.setInterval(() => { if ($('mq-api-key')?.value.trim()) fetchMenthorqLevels(); }, minutes * 60_000) : null; }
function menthorqColor(name) { const value = name.toLowerCase(); if (value.includes('call') || value.includes('resistance')) return '#f05d6c'; if (value.includes('put') || value.includes('support')) return '#29c78a'; if (value.includes('hvl')) return '#4a9eff'; if (value.includes('min') || value.includes('max')) return '#f2994a'; if (value.includes('gamma') || value.includes('wall')) return '#f2bb59'; if (value.includes('blind')) return '#52d4df'; if (value.includes('swing')) return '#d4df52'; return '#9aa8b8'; }
function renderMenthorqLines() { clearMenthorqLines(); if (!menthorqVisible) return; drawMenthorqOverlays(); const list = document.createDocumentFragment(); menthorqLevels.forEach((item) => { const row = document.createElement('div'); row.className = 'level-item'; const swatch = document.createElement('span'); swatch.className = 'level-swatch'; swatch.style.background = menthorqColor(item.name); const name = document.createElement('span'); name.className = 'level-name'; name.textContent = item.name; name.title = item.type; const value = document.createElement('span'); value.className = 'level-value'; value.textContent = fmt(item.price); row.append(swatch, name, value); list.append(row); }); $('menthorq-level-list').append(list); }
function flattenMenthorqLevels(payload) { const records = Array.isArray(payload?.levels) ? payload.levels : []; const levels = []; for (const record of records) { const type = String(record.level_type || record.type || 'intraday'); const kind = String(record.kind || ''); if (!type.toLowerCase().includes('intraday') && kind.toLowerCase() !== 'intraday') continue; const values = Array.isArray(record.level_values) ? record.level_values : Array.isArray(record.values) ? record.values : []; for (const item of values) { const price = Number(item.value ?? item.price); const name = String(item.name || item.label || type); if (Number.isFinite(price)) levels.push({ name, price, type }); } } const unique = new Map(); levels.forEach((item) => unique.set(`${item.name}:${item.price}`, item)); return [...unique.values()].sort((a, b) => b.price - a.price); }
function renderMenthorqLevels(levels) { menthorqLevels = levels; renderMenthorqLines(); refreshIndicatorButton(); }
async function fetchMenthorqLevels() { const settings = menthorqFormSettings(); const ticker = settings.tickers[current.root] || current.root; const status = $('menthorq-status'); if (!settings.apiKey) { status.textContent = 'MQ 未配置'; status.className = ''; openMenthorqSettings(); return; } if (!settings.levelTypes.length) { $('menthorq-message').textContent = '至少选择一种日内数据类型'; $('menthorq-message').classList.add('error'); return; } const requestSeq = ++menthorqRequestSeq; status.textContent = `MQ ${ticker} 加载中`; status.className = ''; $('menthorq-message').textContent = '正在获取日内水平...'; $('menthorq-message').classList.remove('error'); try { const response = await fetch('/api/menthorq/levels', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ apiKey: settings.apiKey, apiUrl: settings.apiUrl, platform: settings.platform, ticker, userId: settings.userId, levelTypes: settings.levelTypes }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || `HTTP ${response.status}`); if (requestSeq !== menthorqRequestSeq) return; const levels = flattenMenthorqLevels(payload); renderMenthorqLevels(levels); status.textContent = `MQ ${ticker} · ${levels.length} 条`; status.className = levels.length ? 'ready' : ''; $('menthorq-message').textContent = levels.length ? `已加载 ${levels.length} 个日内水平，更新时间 ${new Date().toLocaleTimeString()}` : 'API 返回成功，但没有可用的日内水平'; } catch (error) { if (requestSeq !== menthorqRequestSeq) return; menthorqLevels = []; clearMenthorqLines(); refreshIndicatorButton(); status.textContent = 'MQ 加载失败'; status.className = 'error'; $('menthorq-message').textContent = error.message; $('menthorq-message').classList.add('error'); } }
document.querySelectorAll('[data-side]').forEach((button)=>button.onclick=()=>{side=Number(button.dataset.side);document.querySelectorAll('[data-side]').forEach((b)=>b.classList.toggle('active',b===button));}); $('submit-order').onclick=submitOrder; $('refresh-account').onclick=refreshAccount; $('order-type').onchange=()=>{const stop=Number($('order-type').value)===4;$('price2-wrap').classList.toggle('hidden',!stop);};
const CONNECTION_PROFILES_KEY = 'odt-rithmic-profiles-v1';
let connectionState = null, connectionRefreshTimer = null;
function connectionRefreshSoon() { window.clearTimeout(connectionRefreshTimer); connectionRefreshTimer = window.setTimeout(() => { if ($('connection-settings').classList.contains('open') || !connectionState) loadConnectionState(); }, 800); }
async function loadConnectionState(fill = false) { try { const response = await fetch('/api/connection'); const data = await response.json(); if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`); connectionState = data; renderConnectionState(); if (fill) fillConnectionForm(data); } catch (error) { $('connection-state').innerHTML = `<span class="err">无法读取连接状态：${escapeHtml(error.message)}</span>`; } }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (ch) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch])); }
function renderConnectionState() { const data = connectionState; if (!data) return; const sourceLabel = { saved: '服务器保存文件', session: '本次会话（未保存）', env: '专用交易环境变量' }[data.source] || data.source; $('account-label').textContent = data.user || '下单账号'; $('connection-summary').textContent = data.user ? `${data.user} · ${data.systemName || ''}` : '未配置个人下单连接'; $('mode-badge').textContent = data.tradingConnected ? 'PAPER' : 'READ ONLY'; const dot = $('account-dot'); dot.classList.toggle('live', Boolean(data.tradingConnected)); dot.classList.toggle('error', Boolean(data.user) && !data.tradingConnected); const orderState = data.tradingConnected ? '<span class="ok">已连接</span>' : data.user ? '<span class="err">未连接</span>' : '<span>未配置</span>'; $('connection-state').innerHTML = `数据源 <b>服务器行情与历史</b> · ${data.feedAvailable ? '<span class="ok">已连接</span>' : '<span class="err">重连中</span>'}<br>下单连接 ${orderState}${data.user ? `<br>账号 <b>${escapeHtml(data.user)}</b> · 环境 <b>${escapeHtml(data.environment)}</b> · 线路 <b>${escapeHtml(data.systemName)}</b><br>地址 <b>${escapeHtml(data.url || '未设置')}</b> · 来源：${escapeHtml(sourceLabel)}` : ''}${data.lastError ? `<br><span class="err">服务器数据连接：${escapeHtml(data.lastError)}</span>` : ''}`; $('conn-url-list').innerHTML = (data.knownUrls || []).map((url) => `<option value="${escapeHtml(url)}"></option>`).join(''); $('conn-system-list').innerHTML = (data.knownSystems || []).map((name) => `<option value="${escapeHtml(name)}"></option>`).join(''); }
function fillConnectionForm(data) { $('conn-environment').value = data.environment || 'demo'; $('conn-system').value = data.systemName || ''; $('conn-user').value = data.user || ''; $('conn-password').value = ''; $('conn-password').placeholder = data.hasPassword ? '留空则沿用当前密码' : '请输入密码'; $('conn-account-id').value = data.accountId || ''; $('conn-fcm-id').value = data.fcmId || ''; $('conn-ib-id').value = data.ibId || ''; $('conn-url').value = data.url || ''; $('conn-alt-url').value = data.altUrl && data.altUrl !== data.url ? data.altUrl : ''; $('conn-app-name').value = data.appName || ''; $('conn-app-version').value = data.appVersion || ''; }
function connectionForm() { return { environment: $('conn-environment').value, systemName: $('conn-system').value.trim(), user: $('conn-user').value.trim(), password: $('conn-password').value, accountId: $('conn-account-id').value.trim(), fcmId: $('conn-fcm-id').value.trim(), ibId: $('conn-ib-id').value.trim(), url: $('conn-url').value.trim(), altUrl: $('conn-alt-url').value.trim(), appName: $('conn-app-name').value.trim(), appVersion: $('conn-app-version').value.trim() }; }
function connectionMessage(text, error = false) { const box = $('connection-message'); box.textContent = text; box.classList.toggle('error', error); }
function setConnectionBusy(busy) { ['connection-save', 'connection-test', 'connection-reset'].forEach((id) => { $(id).disabled = busy; }); }
async function saveConnection() { const form = connectionForm(); if (!form.user) return connectionMessage('请输入用户名', true); if (!form.url) return connectionMessage('请输入主 WebSocket 地址', true); if (!form.password && !connectionState?.hasPassword) return connectionMessage('请输入密码', true); if (connectionState?.tradingEnabled && (!form.accountId || !form.fcmId || !form.ibId)) return connectionMessage('启用 Paper 交易时必须填写 Account ID、FCM ID 和 IB ID', true); setConnectionBusy(true); connectionMessage('正在连接个人 Rithmic 下单线路…'); try { const response = await fetch('/api/connection', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...form, persist: $('conn-persist').checked }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`); connectionState = data; renderConnectionState(); $('conn-password').value = ''; if (data.tradingConnected) { connectionMessage(`下单连接已切换到 ${data.user} · ${data.systemName}；服务器行情与历史未受影响`); show(`下单账号已连接：${data.user}`); } else { connectionMessage('下单配置已保存，但服务器当前禁止交易；行情与历史仍由服务器提供'); show('下单配置已保存，当前为只读模式'); } refreshAccount(); window.setTimeout(loadConnectionState, 1500); } catch (error) { connectionMessage(`下单连接失败：${error.message}`, true); } finally { setConnectionBusy(false); } }
async function testConnection() { const form = connectionForm(); if (!form.user || !form.url) return connectionMessage('请先填写用户名和主地址', true); setConnectionBusy(true); connectionMessage('正在测试登录（最多 25 秒）…'); try { const response = await fetch('/api/connection/test', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); const systems = data.systems?.length ? `可用线路：${data.systems.join('、')}` : ''; if (!response.ok || !data.ok) throw new Error(`${data.error || `HTTP ${response.status}`}${systems ? `（${systems}）` : ''}`); if (data.systems?.length) $('conn-system-list').innerHTML = data.systems.map((name) => `<option value="${escapeHtml(name)}"></option>`).join(''); connectionMessage(`${data.message}（${data.elapsedMs} ms）${systems ? ' · ' + systems : ''}`); } catch (error) { connectionMessage(`测试失败：${error.message}`, true); } finally { setConnectionBusy(false); } }
async function resetConnection() { if (!confirm('清除个人 Rithmic 下单连接？服务器行情与历史不会受到影响。')) return; setConnectionBusy(true); try { const response = await fetch('/api/connection/reset', { method: 'POST' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`); connectionState = data; renderConnectionState(); fillConnectionForm(data); connectionMessage('个人下单连接已清除，当前为只读模式；服务器行情与历史保持连接'); refreshAccount(); } catch (error) { connectionMessage(`清除失败：${error.message}`, true); } finally { setConnectionBusy(false); } }
function loadConnectionProfiles() { try { return (JSON.parse(localStorage.getItem(CONNECTION_PROFILES_KEY) || '[]') || []).filter((item) => item && item.user); } catch { return []; } }
function saveConnectionProfiles(list) { localStorage.setItem(CONNECTION_PROFILES_KEY, JSON.stringify(list)); renderConnectionProfiles(); }
function renderConnectionProfiles() { const list = loadConnectionProfiles(); $('connection-profiles').innerHTML = list.length ? list.map((item, index) => `<div class="profile-item"><span class="profile-name">${escapeHtml(item.user)}<small>${escapeHtml(item.environment)} · ${escapeHtml(item.systemName || '')}${item.password ? ' · 含密码' : ''}</small></span><button class="use" data-index="${index}">填入</button><button class="del" data-index="${index}" title="删除">×</button></div>`).join('') : '<div class="empty-state">尚未保存账号。填好表单后点击下方按钮即可保存，方便一键切换。</div>'; $('connection-profiles').querySelectorAll('button.use').forEach((button) => button.onclick = () => { const item = list[Number(button.dataset.index)]; if (!item) return; $('conn-environment').value = item.environment || 'demo'; $('conn-system').value = item.systemName || ''; $('conn-user').value = item.user || ''; $('conn-password').value = item.password || ''; $('conn-account-id').value = item.accountId || ''; $('conn-fcm-id').value = item.fcmId || ''; $('conn-ib-id').value = item.ibId || ''; $('conn-url').value = item.url || ''; $('conn-alt-url').value = item.altUrl || ''; if (item.appName) $('conn-app-name').value = item.appName; if (item.appVersion) $('conn-app-version').value = item.appVersion; connectionMessage(`已填入账号 ${item.user}，点击“保存并连接下单”生效`); }); $('connection-profiles').querySelectorAll('button.del').forEach((button) => button.onclick = () => { const next = list.filter((_, index) => index !== Number(button.dataset.index)); saveConnectionProfiles(next); }); }
function addConnectionProfile() { const form = connectionForm(); if (!form.user) return connectionMessage('请先填写用户名', true); const keepPassword = form.password ? confirm('是否把密码一起保存在本浏览器？（明文存储在 localStorage，仅建议在本机使用）') : false; const profile = { ...form, password: keepPassword ? form.password : '' }; const list = loadConnectionProfiles().filter((item) => !(item.user === profile.user && item.environment === profile.environment && (item.systemName || '') === (profile.systemName || ''))); list.push(profile); saveConnectionProfiles(list); connectionMessage(`已保存账号 ${profile.user}`); }
function openConnectionSettings() { $('connection-settings').classList.add('open'); $('connection-settings').setAttribute('aria-hidden', 'false'); $('connection-settings-backdrop').classList.remove('hidden'); loadConnectionState(true); renderConnectionProfiles(); }
function closeConnectionSettings() { $('connection-settings').classList.remove('open'); $('connection-settings').setAttribute('aria-hidden', 'true'); $('connection-settings-backdrop').classList.add('hidden'); }
function initConnectionSettings() { $('connection-settings-open').onclick = openConnectionSettings; $('connection-settings-close').onclick = closeConnectionSettings; $('connection-settings-backdrop').onclick = closeConnectionSettings; $('connection-save').onclick = saveConnection; $('connection-test').onclick = testConnection; $('connection-reset').onclick = resetConnection; $('connection-profile-add').onclick = addConnectionProfile; $('conn-environment').onchange = () => { const defaults = { demo: 'Rithmic Paper Trading', live: 'Rithmic 01', test: 'Rithmic Test' }; const current = $('conn-system').value.trim(); if (!current || Object.values(defaults).includes(current)) $('conn-system').value = defaults[$('conn-environment').value]; }; $('conn-password').onkeydown = (event) => { if (event.key === 'Enter') saveConnection(); }; }
function showMemberGate(message = '', configured = true) { memberAuthenticated = false; $('member-gate').classList.remove('hidden'); $('member-message').textContent = message || (configured ? '' : '服务器尚未配置会员账号，请联系管理员。'); $('connection-label').textContent = '会员未登录'; $('member-label').textContent = '会员登录'; }
function startMemberSession(username) { memberAuthenticated = true; $('member-gate').classList.add('hidden'); $('member-label').textContent = username || '会员'; if (authenticatedStarted) return; authenticatedStarted = true; try { initMenthorq(); } catch (error) { console.error('MenthorQ init failed', error); } loadConnectionState(); connect(); }
async function initMemberAuth() { $('member-login-form').onsubmit = async (event) => { event.preventDefault(); const button = $('member-login-button'); button.disabled = true; $('member-message').textContent = '正在验证会员资格…'; try { const response = await fetch('/api/auth/login', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ username: $('member-username').value.trim(), password: $('member-password').value }) }); const data = await response.json(); if (!response.ok || !data.authenticated) throw new Error(data.error || `HTTP ${response.status}`); $('member-password').value = ''; startMemberSession(data.username); } catch (error) { $('member-message').textContent = error.message; } finally { button.disabled = false; } }; $('member-session-button').onclick = async () => { if (!memberAuthenticated) return $('member-gate').classList.remove('hidden'); if (!confirm('退出会员账号并停止接收行情？')) return; await fetch('/api/auth/logout', { method: 'POST' }); memberAuthenticated = false; authenticatedStarted = false; if (ws) { ws.onclose = null; ws.close(); ws = null; } bars = []; candle.setData([]); line.setData([]); depthBook = new Map(); $('depth').replaceChildren(); showMemberGate('已退出会员账号'); }; try { const response = await fetch('/api/auth/session'); const data = await response.json(); if (data.authenticated) startMemberSession(data.username); else showMemberGate('', data.configured); } catch (error) { showMemberGate(`无法验证会员状态：${error.message}`); } }
buildTabs(); initChart(); initPeriods(); initHistoryDays(); initTimezone(); try { initConnectionSettings(); } catch (error) { console.error('Connection settings init failed', error); } initMemberAuth(); window.__terminalBooted = true;

function loadOverlaySettings() { let stored = {}, savedIndicators = {}, savedDrawings = {}; try { stored = JSON.parse(localStorage.getItem(OVERLAY_STORAGE_KEY) || '{}'); } catch { stored = {}; } try { savedIndicators = JSON.parse(localStorage.getItem(INDICATOR_SETTINGS_KEY) || '{}'); } catch { savedIndicators = {}; } try { savedDrawings = JSON.parse(localStorage.getItem(DRAWINGS_STORAGE_KEY) || '{}'); } catch { savedDrawings = {}; } const settings = { ...OVERLAY_DEFAULTS, ...(stored && typeof stored === 'object' ? stored : {}) }; menthorqVisible = Boolean(settings.menthorq); largeOrdersVisible = Boolean(settings.largeOrders); vwapVisible = Boolean(settings.vwap); indicatorSettings = { largeOrders: { ...INDICATOR_DEFAULTS.largeOrders, ...(savedIndicators.largeOrders || {}) }, vwap: { ...INDICATOR_DEFAULTS.vwap, ...(savedIndicators.vwap || {}) } }; drawingsBySymbol = savedDrawings && typeof savedDrawings === 'object' ? savedDrawings : {}; }
function saveOverlaySettings() { localStorage.setItem(OVERLAY_STORAGE_KEY, JSON.stringify({ menthorq: menthorqVisible, largeOrders: largeOrdersVisible, vwap: vwapVisible })); }
function saveIndicatorSettings() { localStorage.setItem(INDICATOR_SETTINGS_KEY, JSON.stringify(indicatorSettings)); }
function overlayActive() { return (menthorqVisible && menthorqLevels.length > 0) || largeOrdersVisible || vwapVisible; }
function refreshIndicatorButton() { $('indicators-open')?.classList.toggle('active', overlayActive()); }
function syncOverlayInputs() { const menu = $('indicators-menu'); if (!menu) return; const menthorqInput = menu.querySelector('input[data-overlay="menthorq"]'), largeInput = menu.querySelector('input[data-overlay="large-orders"]'), vwapInput = menu.querySelector('input[data-overlay="vwap"]'); if (menthorqInput) menthorqInput.checked = menthorqVisible; if (largeInput) largeInput.checked = largeOrdersVisible; if (vwapInput) vwapInput.checked = vwapVisible; }
function setMenthorqVisible(visible) { menthorqVisible = Boolean(visible); saveOverlaySettings(); renderMenthorqLines(); syncOverlayInputs(); refreshIndicatorButton(); }
function closeIndicatorSettings() { $('indicator-settings').classList.remove('open'); $('indicator-settings').setAttribute('aria-hidden', 'true'); $('indicator-settings-backdrop').classList.add('hidden'); }
function populateIndicatorSettings() { const large = indicatorSettings.largeOrders, vwap = indicatorSettings.vwap; $('large-order-threshold').value = large.threshold; $('large-order-buy-color').value = large.buyColor; $('large-order-sell-color').value = large.sellColor; $('large-order-labels').checked = large.labels; $('vwap-anchor').value = vwap.anchor; $('vwap-session-start').value = vwap.sessionStart; $('vwap-custom-time').value = vwap.customTime; $('vwap-source').value = vwap.source; $('vwap-line-width').value = String(vwap.lineWidth); $('vwap-color').value = vwap.color; updateVwapSettingVisibility(); }
function openIndicatorSettings(kind) { const large = kind === 'large-orders'; $('indicator-settings-title').textContent = large ? '大单成交设置' : 'VWAP 设置'; $('large-order-settings').classList.toggle('hidden', !large); $('vwap-settings').classList.toggle('hidden', large); $('indicator-settings').dataset.kind = kind; populateIndicatorSettings(); $('indicator-settings').classList.add('open'); $('indicator-settings').setAttribute('aria-hidden', 'false'); $('indicator-settings-backdrop').classList.remove('hidden'); }
function updateVwapSettingVisibility() { const anchor = $('vwap-anchor').value; $('vwap-session-wrap').classList.toggle('hidden', anchor !== 'session'); $('vwap-custom-wrap').classList.toggle('hidden', anchor !== 'custom'); }
function applyIndicatorSettings() { const threshold = Math.floor(Number($('large-order-threshold').value)); if (!(threshold >= 1)) return show('大单阈值必须大于 0'); indicatorSettings.largeOrders = { threshold, buyColor: $('large-order-buy-color').value, sellColor: $('large-order-sell-color').value, labels: $('large-order-labels').checked }; indicatorSettings.vwap = { anchor: $('vwap-anchor').value, sessionStart: $('vwap-session-start').value || '18:00', customTime: $('vwap-custom-time').value, source: $('vwap-source').value, color: $('vwap-color').value, lineWidth: Number($('vwap-line-width').value) || 2 }; saveIndicatorSettings(); closeIndicatorSettings(); renderIndicators(); scheduleDrawingDraw(); }
function initIndicatorSettings() { $('indicator-settings-close').onclick = closeIndicatorSettings; $('indicator-settings-backdrop').onclick = closeIndicatorSettings; $('vwap-anchor').onchange = updateVwapSettingVisibility; $('indicator-settings-save').onclick = applyIndicatorSettings; $('indicator-settings-reset').onclick = () => { const kind = $('indicator-settings').dataset.kind; if (kind === 'large-orders') indicatorSettings.largeOrders = { ...INDICATOR_DEFAULTS.largeOrders }; else indicatorSettings.vwap = { ...INDICATOR_DEFAULTS.vwap }; populateIndicatorSettings(); }; document.querySelectorAll('[data-indicator-settings]').forEach((button) => button.onclick = (event) => { event.stopPropagation(); openIndicatorSettings(button.dataset.indicatorSettings); }); }
function initOverlays(menu) { syncOverlayInputs(); $('indicators-open').onclick = (event) => { event.stopPropagation(); menu.classList.toggle('hidden'); }; menu.onclick = (event) => event.stopPropagation(); document.addEventListener('click', () => menu.classList.add('hidden')); const menthorqInput = menu.querySelector('input[data-overlay="menthorq"]'), largeInput = menu.querySelector('input[data-overlay="large-orders"]'), vwapInput = menu.querySelector('input[data-overlay="vwap"]'); if (menthorqInput) menthorqInput.onchange = () => { const wanted = menthorqInput.checked; setMenthorqVisible(wanted); if (wanted && !menthorqLevels.length) { if ($('mq-api-key')?.value.trim()) fetchMenthorqLevels(); else openMenthorqSettings(); } }; if (largeInput) largeInput.onchange = () => { largeOrdersVisible = largeInput.checked; saveOverlaySettings(); if (largeOrdersVisible && !bars.some((bar) => bar.levels?.length)) loadHistory(); else renderIndicators(); syncOverlayInputs(); }; if (vwapInput) vwapInput.onchange = () => { vwapVisible = vwapInput.checked; saveOverlaySettings(); renderIndicators(); syncOverlayInputs(); }; initIndicatorSettings(); refreshIndicatorButton(); }
